[package]
name = "posixutils-calc"
version = "0.1.12"
edition = "2021"

[dependencies]
plib = { path = "../plib" }
gettext-rs.workspace = true
regex.workspace = true
clap.workspace = true
pest = { version = "2.7", default-features = false }
pest_derive = "2.7"
lazy_static = "1.4"
bigdecimal = "0.4"
rustyline = { version = "14.0", default-features = false }

[[bin]]
name = "expr"
path = "src/expr.rs"

[[bin]]
name = "bc"
path = "src/bc.rs"
