[package]
name = "posixutils-misc"
version = "0.1.12"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
atty.workspace = true
libc.workspace = true
gettext-rs.workspace = true

[[bin]]
name = "true"
path = "src/true.rs"

[[bin]]
name = "false"
path = "src/false.rs"

[[bin]]
name = "test"
path = "src/test.rs"

