[workspace]
resolver = "2"

members = [
	"calc",
	"datetime",
	"dev",
	"display",
	"file",
	"fs",
	"misc",
	"pathnames",
	"plib",
	"process",
	"sccs",
	"screen",
	"sys",
	"text",
	"tree",
	"users",
	"xform"
]

[workspace.dependencies]
atty = "0.2"
clap = { version = "4", default-features = false, features = ["std", "derive", "help", "usage"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
gettext-rs = { version = "0.7", features = ["gettext-system"] }
libc = "0.2"
regex = "1.10"
