[package]
name = "posixutils-sys"
version = "0.1.12"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
uname = "0.1"
libc.workspace = true
chrono.workspace = true

[[bin]]
name = "getconf"
path = "src/getconf.rs"

[[bin]]
name = "ipcrm"
path = "src/ipcrm.rs"

[[bin]]
name = "ipcs"
path = "src/ipcs.rs"

[[bin]]
name = "uname"
path = "src/uname.rs"

[[bin]]
name = "who"
path = "src/who.rs"

