[package]
name = "posixutils-dev"
version = "0.1.12"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
object =  { version = "0.35", features = ["read", "build", "elf"]}
chrono.workspace = true
regex.workspace = true
ar = "0.9"
regex-syntax = "0.8"

[[bin]]
name = "lex"
path = "src/lex.rs"

[[bin]]
name = "nm"
path = "src/nm.rs"

[[bin]]
name = "ar"
path = "src/ar.rs"
required-features = ["object/read_core", "object/archive"]

[[bin]]
name = "strip"
path = "src/strip.rs"

[[bin]]
name = "strings"
path = "src/strings.rs"
