[package]
name = "posixutils-users"
version = "0.1.12"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
libc.workspace = true
atty.workspace = true
chrono.workspace = true
syslog = "6.1"

[[bin]]
name = "id"
path = "src/id.rs"

[[bin]]
name = "logname"
path = "src/logname.rs"

[[bin]]
name = "logger"
path = "src/logger.rs"

[[bin]]
name = "mesg"
path = "src/mesg.rs"

[[bin]]
name = "pwd"
path = "src/pwd.rs"

[[bin]]
name = "tty"
path = "src/tty.rs"

[[bin]]
name = "write"
path = "src/write.rs"

