[package]
name = "posixutils-process"
version = "0.1.12"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
libc.workspace = true
atty.workspace = true
errno = "0.3"
dirs = "5.0"

[[bin]]
name = "env"
path = "src/env.rs"

[[bin]]
name = "kill"
path = "src/kill.rs"

[[bin]]
name = "nice"
path = "src/nice.rs"

[[bin]]
name = "nohup"
path = "src/nohup.rs"

[[bin]]
name = "renice"
path = "src/renice.rs"

[[bin]]
name = "xargs"
path = "src/xargs.rs"

