[package]
name = "posixutils-text"
version = "0.1.12"
edition = "2021"
authors = ["Jeff Garzik"]
license = "MIT"
repository = "https://github.com/rustcoreutils/posixutils-rs.git"

[dependencies]
plib = { path = "../plib" }
clap.workspace = true
gettext-rs.workspace = true
topological-sort = "0.2"
regex.workspace = true
chrono.workspace = true
libc.workspace = true
notify-debouncer-full = "0.3"
ctor = "0.2"
atty.workspace = true
diff = "0.1"
dirs = "5.0"
deunicode = "1.6"

[[bin]]
name = "asa"
path = "src/asa.rs"

[[bin]]
name = "comm"
path = "src/comm.rs"

[[bin]]
name = "unexpand"
path = "src/unexpand.rs"

[[bin]]
name = "csplit"
path = "src/csplit.rs"

[[bin]]
name = "diff"
path = "src/diff.rs"

[[bin]]
name = "cut"
path = "src/cut.rs"

[[bin]]
name = "uniq"
path = "src/uniq.rs"

[[bin]]
name = "sort"
path = "src/sort.rs"

[[bin]]
name = "expand"
path = "src/expand.rs"

[[bin]]
name = "tr"
path = "src/tr.rs"

[[bin]]
name = "fold"
path = "src/fold.rs"

[[bin]]
name = "head"
path = "src/head.rs"

[[bin]]
name = "tail"
path = "src/tail.rs"

[[bin]]
name = "nl"
path = "src/nl.rs"

[[bin]]
name = "paste"
path = "src/paste.rs"

[[bin]]
name = "pr"
path = "src/pr.rs"

[[bin]]
name = "tsort"
path = "src/tsort.rs"

[[bin]]
name = "wc"
path = "src/wc.rs"

